package br.edu.qi.model;
// Generated 29/10/2018 21:06:07 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario",
         catalog = "dbpersonalmoney"
)
public class Usuario implements java.io.Serializable {

    private int idUsuario;
    private String nome;
    private String senha;
    private double saldoAtual;

    public Usuario() {
    }

    public Usuario(String nome, String senha, double saldoAtual) {
        this.nome = nome;
        this.senha = senha;
        this.saldoAtual = saldoAtual;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idUsuario", unique = true, nullable = false)
    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name = "nome", nullable = false, length = 30)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "senha", nullable = false, length = 12)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    @Column(name = "saldoAtual", nullable = false, precision = 22, scale = 0)
    public double getSaldoAtual() {
        return this.saldoAtual;
    }

    public void setSaldoAtual(double saldoAtual) {
        this.saldoAtual = saldoAtual;
    }

}
