package br.edu.qi.model;
// Generated 07/11/2018 20:47:15 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="dbpersonalmoney"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nome;
     private String senha;
     private String pergunta;
     private String resposta;

    public Usuario() {
    }

    public Usuario(String nome, String senha, String pergunta, String resposta) {
       this.nome = nome;
       this.senha = senha;
       this.pergunta = pergunta;
       this.resposta = resposta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nome", nullable=false, length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="senha", nullable=false, length=12)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="pergunta", nullable=false, length=30)
    public String getPergunta() {
        return this.pergunta;
    }
    
    public void setPergunta(String pergunta) {
        this.pergunta = pergunta;
    }

    
    @Column(name="resposta", nullable=false, length=30)
    public String getResposta() {
        return this.resposta;
    }
    
    public void setResposta(String resposta) {
        this.resposta = resposta;
    }




}


