package br.edu.qi.model;
// Generated 16/11/2018 10:59:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="dbpersonalmoney"
)
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nome;
     private String senha;
     private double valorBanco;
     private double valorCasa;

    public Usuario() {
    }

    public Usuario(String nome, String senha, double valorBanco, double valorCasa) {
       this.nome = nome;
       this.senha = senha;
       this.valorBanco = valorBanco;
       this.valorCasa = valorCasa;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
     @Column(name="idUsuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nome", nullable=false, length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="senha", nullable=false, length=10)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="valorBanco", nullable=false, precision=22, scale=0)
    public double getValorBanco() {
        return this.valorBanco;
    }
    
    public void setValorBanco(double valorBanco) {
        this.valorBanco = valorBanco;
    }

    
    @Column(name="valorCasa", nullable=false, precision=22, scale=0)
    public double getValorCasa() {
        return this.valorCasa;
    }
    
    public void setValorCasa(double valorCasa) {
        this.valorCasa = valorCasa;
    }




}


